# QUAAF Returns

#### Import Packages

In [1]:
import numpy as np                      # Linear algebra
import pandas as pd                     # Dataframes
from collections import defaultdict     # For dictionaries of dataframes

pd.options.mode.chained_assignment = None  # default='warn'

#### Load Holding Data

In [2]:
filename = 'holdings-RD.xlsx'

holdings = pd.ExcelFile(filename)

sheet_names = holdings.sheet_names  # Get list of sheets
sheet_names                         # Print list of sheets

['summary',
 'growth_cad',
 'growth_usd',
 'market_neutral_cad',
 'market_neutral_usd',
 'sustainability_cad',
 'sustainability_usd',
 'thematic_cad',
 'thematic_usd',
 'special_situations_cad',
 'special_situations_usd',
 'conservative_tactical_cad',
 'conservative_tactical_usd',
 'original']

In [3]:
# Load Summary Data
holdings_summary = pd.read_excel(filename, sheet_name = sheet_names[0], header = 5)

In [4]:
# Inspect Data
holdings_summary

,Month,Year,Date,Check,QUAAF,Total Holdings (CAD),CAD Investments,CAD Equivalent of USD Investments,Exchange Rate,USD Investments,...,Thematic (CAD),Thematic (CAD)[trans],Thematic (USD),Thematic (USD)[trans],Special Situations (CAD),Special Situations (CAD)[trans],Special Situations (USD),Special Situations (USD)[trans],Conservative Tactical (CAD),Conservative Tactical (USD)
0,2012-01-31 00:00:00,2012-01-31,2012-01-31,0,0.0,0.000,0.00,0.000,NaN,0,...,0,0.00,0,0.00,0,0.0,0,0,0.00,0
1,2012-02-29 00:00:00,2012-02-29,2012-02-29,0,25000.0,25000.000,25000.00,0.000,NaN,0,...,0,0.00,0,0.00,0,0.0,0,0,25000.00,0
2,2012-03-31 00:00:00,2012-03-31,2012-03-31,0,175065.0,175065.000,175065.00,0.000,NaN,0,...,0,0.00,0,0.00,0,0.0,0,0,155038.00,0
3,2012-04-30 00:00:00,2012-04-30,2012-04-30,0,174766.0,174766.000,174766.00,0.000,NaN,0,...,0,0.00,0,0.00,0,0.0,0,0,115052.00,0
4,2012-05-31 00:00:00,2012-05-31,2012-05-31,0,174885.0,174885.000,174885.00,0.000,NaN,0,...,0,0.00,0,0.00,0,0.0,0,0,115167.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,Nov,2020-11-30,2020-11-30,0,537935.0,537935.366,517140.00,20795.366,1.2955,16052,...,2673,0.00,16052,0.00,0,0.0,0,0,43315.00,0
107,Dec,2020-12-31,2020-12-31,0,560038.0,560037.925,534784.00,25253.925,1.2750,19807,...,4562,1405.00,20849,1042.06,0,0.0,0,0,41927.00,-1042
108,Jan,2021-01-31,2021-01-31,0,575999.0,575998.858,549521.00,26477.858,1.2790,20702,...,4802,0.00,20704,0.00,0,0.0,0,0,39149.00,-2
109,Feb,2021-01-31,2021-02-28,0,591546.0,591545.740,560225.00,31320.740,1.2700,24662,...,3404,-1340.78,7380,-17284.93,0,0.0,0,0,25507.00,17282
110,Mar,2021-01-31,2021-03-31,0,603978.0,603977.780,573080.06,30897.720,1.2600,24522,...,2461,0.00,7240,0.00,0,0.0,0,0,89345.06,17282

#### Data Cleaning

In [5]:
# Extract columns relevant for return by fund group
col_keep = ['Date','Growth (Total)', 'Growth (Total)[trans]',
            'Market Neutral (Total)', 'Market Neutral (Total)[trans]',
            'Sustainability (Total)', 'Sustainability (Total)[trans]',
            'Thematic (Total)', 'Thematic (Total)[trans]',
            'Special Situations (Total)', 'Special Situations (Total)[trans]',
            'Conservative Tactical (Total)', 'Conservative Tactical (Total)[trans]']

holdings_summary = holdings_summary[holdings_summary.columns[holdings_summary.columns.isin(col_keep)]]

In [6]:
# Reset index to date
holdings_summary.set_index('Date', inplace=True)
holdings_summary.index.name = None

In [7]:
# Replace NaNs with 0s (No position = $0 position)
holdings_summary = holdings_summary.fillna(0)

In [8]:
# Inspect cleaned dataframe
holdings_summary

,Growth (Total),Growth (Total)[trans],Market Neutral (Total),Market Neutral (Total)[trans],Sustainability (Total),Sustainability (Total)[trans],Thematic (Total),Thematic (Total)[trans],Special Situations (Total),Special Situations (Total)[trans],Conservative Tactical (Total),Conservative Tactical (Total)[trans]
2012-01-31,0,0.00,0.0,0.0,0,0,0.000,0.0000,0,0.0,0.000,0.0
2012-02-29,0,0.00,0.0,0.0,0,0,0.000,0.0000,0,0.0,25000.000,0.0
2012-03-31,0,0.00,20027.0,20000.0,0,0,0.000,0.0000,0,0.0,155038.000,0.0
2012-04-30,0,0.00,59714.0,40000.0,0,0,0.000,0.0000,0,0.0,115052.000,0.0
2012-05-31,0,0.00,59718.0,0.0,0,0,0.000,0.0000,0,0.0,115167.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-30,167594,0.00,303558.0,0.0,0,0,23468.366,0.0000,0,0.0,43315.000,0.0
2020-12-31,175801,0.00,312494.0,0.0,0,0,31144.475,2733.6265,0,0.0,40598.450,0.0
2021-01-31,185987,0.00,319583.0,0.0,0,0,31282.416,0.0000,0,0.0,39146.442,0.0
2021-02-28,194389,0.00,321869.0,0.0,15056,15000,12776.600,-23292.6411,0,0.0,47455.140,0.0
2021-03-31,139663,-62823.28,326844.0,0.0,14767,0,11583.400,0.0000,0,0.0,111120.380,0.0

# Calculate Returns

#### Define functions to calculate returns

In [9]:
def get_returns(fund_num, input_df):
    fund = my_funds[fund_num]                               # pick fund
    trans = my_funds_trans[fund_num]                        # pick corresponding transactions

    df_fund = input_df[fund].reset_index()                     # extract relevant fund data
    df_trans = input_df[trans].reset_index()                   # extract relevant transaction data

    investment_date_index = df_fund.ne(0).idxmax()[fund]    # Index of row with first non-zero value in fund (initial investment)
    df_fund = df_fund.iloc[investment_date_index:]          # Trim leading rows with zeros from fund data
    df_trans = df_trans.iloc[investment_date_index:]        # Trim leading rows with zeros from transaction data
    df_all = df_fund.join(df_trans[trans])                  # Combine fund and transaction data
    df_all.set_index('index', inplace=True)                 # Reset index to dates
    df_all.index.name = None                                # Remove 'index' heading from index

    investment_periods = len(input_df) - investment_date_index # Number of periods fund has been held

    fund_returns = defaultdict(pd.DataFrame)
    fund_return = df_all                                    #pull a fund out of data frame
    
    # Return calcluations
    fund_return['months'] = range(1, 1+len(fund_return))     # number of holding period
    
    fund_return["1m_return"] = round(100*(fund_return[fund]-fund_return[fund].shift(1)-fund_return[trans])/(fund_return[fund].shift(1)),2)
    
    # Set initial investment for benchmarking. Currently using $100
    benchmark = 100
    if(fund_return[trans][0]>0):
        dollar_growth = [benchmark*(1+((fund_return[fund][0]-fund_return[trans][0])/fund_return[trans][0]))]
    else:
        dollar_growth = [benchmark]     # Fix for portfolios that have no holdings
    
    for i in range(1,len(fund_return['1m_return'])):
        dollar_growth.append(dollar_growth[i-1]*(1+fund_return['1m_return'][i]/100))
    
    fund_return['$1_growth'] = dollar_growth
    # fund_return['$1_growth'] = fund_return['$1_growth'].shift(1)*(1+fund_return["1m_return"]/100)
    fund_return["3m_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'].shift(3))/fund_return['$1_growth'].shift(3)),2)
    fund_return["6m_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'].shift(6))/fund_return['$1_growth'].shift(6)),2)
    fund_return["1y_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'].shift(12))/fund_return['$1_growth'].shift(12)),2)
    fund_return["2y_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'].shift(24))/fund_return['$1_growth'].shift(24)),2)
    fund_return["2y_return_annualized"] = round(100*((1+fund_return["2y_return"]/100)**(1/2)-1),2)
    fund_return["3y_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'].shift(36))/fund_return['$1_growth'].shift(36)),2)
    fund_return["3y_return_annualized"] = round(100*((1+fund_return["3y_return"]/100)**(1/3)-1),2)
    fund_return["5y_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'].shift(60))/fund_return['$1_growth'].shift(60)),2)
    fund_return["5y_return_annualized"] = round(100*((1+fund_return["5y_return"]/100)**(1/5)-1),2)
    fund_return["SI_return"] = round(100*((fund_return['$1_growth']-fund_return['$1_growth'][0])/fund_return['$1_growth'][0]),2)
    fund_return['annualized_return'] = round(100*(fund_return['$1_growth']**(12/fund_return['months'])-1),2)


    #########
    # # Taken out Mar 16    
    # trans_neg = fund_return[trans].where(fund_return[trans]<0,0)
    # trans_pos = fund_return[trans].where(fund_return[trans]>0,0)
    # fund_return['money_in_sum'] = trans_pos.expanding(min_periods=1).sum()
    # fund_return['money_out_sum'] = -1*trans_neg.expanding(min_periods=1).sum()
    #     
    # fund_return['net_gains'] = -fund_return['money_in_sum'] + fund_return[fund] + fund_return['money_out_sum']
    # fund_return['unrealized_gains'] = np.where(fund_return[fund] <= 0, 0, (fund_return['net_gains'] - fund_return['money_out_sum']))
    ########

    fund_return['volatility'] = 100*((fund_return['1m_return']/100).expanding(min_periods=1).std())
    fund_return['annualized_volatility'] = fund_return['volatility']*np.sqrt(fund_return['months'])

    fund_returns[fund] = fund_return

    return fund_returns[fund]


def compile_returns(input_df):
    # Extract fund names and transaction names from df
    
    global fundcols
    fundcols = list(input_df.columns.values) 
    global my_funds
    my_funds = fundcols[::2]
    global my_funds_trans
    my_funds_trans = fundcols[1::2]

    # Use a for loop to run get_return on each fund in my_funds & store each df in a list
    global returns_list     #<-- making this global allows you to access the intermediate result later
    returns_list = []

    for i in range(0,len(my_funds)):
        returns = get_returns(i, input_df)
        returns_list.append(returns)
    
    # Use a for loop to select the last row in every df in returns_list
    tails_list = []

    for i in range(0,len(returns_list)):
        tails = returns_list[i].tail(1)
        tails.rename(columns={ tails.columns[0]: "Position" }, inplace = True)
        dropcol = my_funds_trans[i]
        tails.drop(columns=dropcol, inplace=True)
        tails_list.append(tails)
    
    for i in tails_list:
        i.columns = ['Position_Value','Months','1M_Return','$100_Growth','3M_Return','6M_Return','1Y_Return','2Y_Return','2Y_Return_Annualized','3Y_Return','3Y_Return_Annualized','5Y_Return','5Y_Return_Annualized','SI_Return','Annualized_Return','Volatility', 'Annualized_Volatility']

    summary_df = pd.concat(tails_list, axis=0)

    summary_df.insert(0, column = 'Position_Name', value = my_funds)

    # summary_df = summary_df[summary_df['Position_Value'] != 0]  # Drop outdated positions

    summary_df.fillna('-', inplace=True)    # Replace NaNs with "-"

    
    return summary_df

## Holdings Summary Returns

In [21]:
returns_holdings_summary = compile_returns(holdings_summary)
returns_holdings_summary

,Position_Name,Position_Value,Months,1M_Return,$100_Growth,3M_Return,6M_Return,1Y_Return,2Y_Return,2Y_Return_Annualized,3Y_Return,3Y_Return_Annualized,5Y_Return,5Y_Return_Annualized,SI_Return,Annualized_Return,Volatility,Annualized_Volatility
2021-03-31,Growth (Total),139663.00,84,4.17,179.646,15.18,19.83,53.99,55.89,24.86,53.91,15.46,86.63,13.29,79.65,109.92,2.65477,24.3314
2021-03-31,Market Neutral (Total),326844.00,109,1.55,117.138,4.6,9.22,13.03,18.92,9.05,17.39,5.49,20.79,3.85,16.98,68.95,1.41806,14.805
2021-03-31,Sustainability (Total),14767.00,2,-1.92,98.4462,-,-,-,-,-,-,-,-,-,-1.92,9.10317e+13,-,-
2021-03-31,Thematic (Total),11583.40,9,-9.34,372.695,4.99,40.38,-,-,-,-,-,-,-,215.73,268108,22.9089,68.7268
2021-03-31,Special Situations (Total),0.00,70,-,-,-,-,-,-,-,-,-,-,-,-,-,4.27517,35.7686
2021-03-31,Conservative Tactical (Total),111120.38,110,134.16,444.448,173.69,90.84,186.82,43.39,19.75,14.26,4.54,-2.9,-0.59,344.45,94.47,58.8963,617.709

#### Export summary dataframe

In [11]:
returns_holdings_summary.to_csv('returns_summary.csv')

In [34]:
# Print total portfolio histories
for fund in range(0,len(my_funds)-2):   # Only print Growth, Market Neutral, Sustainability, Thematic
    filename = 'returns_total/returns_'+my_funds[fund]+'.csv'
    returns_list[fund].to_csv(filename)

## Individual Fund Returns

In [12]:
wanted_sheets = sheet_names[1:11]
wanted_sheets

['growth_cad',
 'growth_usd',
 'market_neutral_cad',
 'market_neutral_usd',
 'sustainability_cad',
 'sustainability_usd',
 'thematic_cad',
 'thematic_usd',
 'special_situations_cad',
 'special_situations_usd']

In [13]:
# Load data

individual_holdings = defaultdict(pd.DataFrame)

for sheet_name in wanted_sheets:
    individual_holdings[sheet_name] = pd.read_excel(filename, sheet_name = sheet_name, header = 5)
    individual_holdings[sheet_name].drop(columns=['Month','Year'], inplace=True)

    # Reset index to date
    individual_holdings[sheet_name].set_index('Date', inplace=True)
    individual_holdings[sheet_name].index.name = None

    # Replace NaNs with 0s (No position = $0 position)
    individual_holdings[sheet_name] = individual_holdings[sheet_name].fillna(0)

In [14]:
individual_holdings['thematic_usd']

,Total,Transactions,Zillow Group Inc.,Zillow Group Inc. [trans],SQUARE Inc.,SQUARE Inc.[trans],Sea Limited,Sea Limited [trans],Mitek Systems Inc,Mitek Systems Inc[trans],Mercadolibre Inc,Mercadolibre Inc[trans],ABBVIE INC,ABBVIE INC[trans],ALECTOR INC,ALECTOR INC[trans],ZYMEWORKS INC,ZYMEWORKS INC[trans]
2012-01-31,0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0
2012-02-29,0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0
2012-03-31,0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0
2012-04-30,0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0
2012-05-31,0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-30,16052,0.00,2911.0,0.00,1899.0,0.00,2164.0,0.0,4418.0,0.00,4660.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0
2020-12-31,20849,1042.06,3505.0,0.00,1959.0,0.00,2389.0,0.0,3272.0,-3728.23,5026.0,0.00,2357.0,2263.31,923.0,962.58,1418.0,1544.4
2021-01-31,20704,0.00,3522.0,0.00,1944.0,0.00,2601.0,0.0,2972.0,0.00,5339.0,0.00,2284.0,0.00,1027.0,0.00,1015.0,0.0
2021-02-28,7380,-17284.93,0.0,-5569.33,0.0,-2487.31,0.0,-3354.6,2812.0,0.00,0.0,-5845.09,2370.0,-28.60,1109.0,0.00,1089.0,0.0
2021-03-31,7240,0.00,0.0,0.00,0.0,0.00,0.0,0.0,2683.0,0.00,0.0,0.00,2381.0,0.00,1229.0,0.00,947.0,0.0

In [15]:
# Get Returns

returns_individual_holdings = defaultdict(pd.DataFrame)

for sheet_name in wanted_sheets:
    returns_individual_holdings[sheet_name] = compile_returns(individual_holdings[sheet_name])

In [16]:
# Look at sample

returns_individual_holdings['thematic_usd']

,Position_Name,Position_Value,Months,1M_Return,$100_Growth,3M_Return,6M_Return,1Y_Return,2Y_Return,2Y_Return_Annualized,3Y_Return,3Y_Return_Annualized,5Y_Return,5Y_Return_Annualized,SI_Return,Annualized_Return,Volatility,Annualized_Volatility
2021-03-31,Total,7240.0,6,-1.9,156.611,16.05,-,-,-,-,-,-,-,-,64.3,2.45259e+06,11.585265,28.377988
2021-03-31,Zillow Group Inc.,0.0,6,-,-,-,-,-,-,-,-,-,-,-,-,-,24.017438,58.830468
2021-03-31,SQUARE Inc.,0.0,6,-,-,-,-,-,-,-,-,-,-,-,-,-,18.225465,44.643088
2021-03-31,Sea Limited,0.0,6,-,-,-,-,-,-,-,-,-,-,-,-,-,9.175440,22.475146
2021-03-31,Mitek Systems Inc,2683.0,6,-4.59,117.513,-18,-,-,-,-,-,-,-,-,22.94,1.38083e+06,28.936134,70.878763
2021-03-31,Mercadolibre Inc,0.0,6,-,-,-,-,-,-,-,-,-,-,-,-,-,10.135553,24.826932
2021-03-31,ABBVIE INC,2381.0,4,0.46,106.464,2.23,-,-,-,-,-,-,-,-,2.23,1.20674e+08,4.070250,8.140500
2021-03-31,ALECTOR INC,1229.0,4,10.82,127.675,33.15,-,-,-,-,-,-,-,-,33.15,2.0812e+08,1.783825,3.567651
2021-03-31,ZYMEWORKS INC,947.0,4,-13.04,61.3178,-33.22,-,-,-,-,-,-,-,-,-33.22,2.30547e+07,17.912088,35.824176

In [17]:
# Write all individual returns to csv files (SHOULD THIS BE GOING TO SINGLE EXCEL?)
for sheet_name in wanted_sheets:
    filename = 'returns/returns_individual-'+sheet_name+'.csv'
    returns_individual_holdings[sheet_name].insert(0, column='Portfolio', value=sheet_name)
    returns_individual_holdings[sheet_name].to_csv(filename)

# Inspect individual portfolio and individual holding

In [18]:
examine_holding = compile_returns(individual_holdings['growth_cad'])
examine_holding

,Position_Name,Position_Value,Months,1M_Return,$100_Growth,3M_Return,6M_Return,1Y_Return,2Y_Return,2Y_Return_Annualized,3Y_Return,3Y_Return_Annualized,5Y_Return,5Y_Return_Annualized,SI_Return,Annualized_Return,Volatility,Annualized_Volatility
2021-03-31,Total,139663.0,84,4.17,179.646,15.18,19.83,53.99,55.89,24.86,53.91,15.46,86.63,13.29,79.65,109.92,2.654774,24.331407
2021-03-31,"DYNAMIC GLOBAL GROWTH OPPORTUNITIES FUND,SER F...",42025.0,23,-3.22,168.101,5.7,17.97,68.66,-,-,-,-,-,-,70.02,1349.33,6.012974,28.837209
2021-03-31,LYNWOOD OPPORTUNITIES FUND CL F (1033),63105.0,18,14,252.393,38.14,43.34,141.76,-,-,-,-,-,-,152.39,3893.79,8.351683,35.433190
2021-03-31,NEWGEN EQUITY LONG-SHORT FUND LP CLASS F (104),34533.0,18,2.66,138.137,14.59,18.93,34.83,-,-,-,-,-,-,38.14,2572.22,2.933156,12.444326
2021-03-31,EHP ADVANTAGE FUND CL F 2013 LEAD SERIES (101F),0.0,72,1.37,125.63,4.32,4.17,14.43,10.52,5.13,14.06,4.48,32.46,5.78,25.63,123.79,2.133966,18.107302
2021-03-31,VANTAGE CLASS F SERIES I 2014 SERIES 1 (201),0.0,56,-,-,-,-,-,-,-,-,-,-,-,-,-,3.165194,23.686146
2021-03-31,FG GLOBAL OPPORTUNITIES CLASS F SUBS (900),0.0,84,-,-,-,-,-,-,-,-,-,-,-,-,-,4.933994,45.220803
2021-03-31,VERTEX FUND CLASS F (301),0.0,83,-,-,-,-,-,-,-,-,-,-,-,-,-,4.307844,39.246327

In [19]:
examine_holding_individual = returns_list[1]
examine_holding_individual

,"DYNAMIC GLOBAL GROWTH OPPORTUNITIES FUND,SER F(2784)","DYNAMIC GLOBAL GROWTH OPPORTUNITIES FUND,SER F(2784)[trans]",months,1m_return,$1_growth,3m_return,6m_return,1y_return,2y_return,2y_return_annualized,3y_return,3y_return_annualized,5y_return,5y_return_annualized,SI_return,annualized_return,volatility,annualized_volatility
2019-05-31,24718.0,25000.0,1,NaN,98.872000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,8.727299e+25,NaN,NaN
2019-06-30,26017.0,0.0,2,5.26,104.072667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.26,1.270633e+14,NaN,NaN
2019-07-31,27458.0,0.0,3,5.54,109.838293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.09,1.455510e+10,0.197990,0.342929
2019-08-31,26356.0,0.0,4,-4.01,105.433777,6.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.64,1.172031e+08,5.434670,10.869339
2019-09-30,23785.0,0.0,5,-9.75,95.153984,-8.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.76,5.600373e+06,7.467963,16.698872
2019-10-31,23701.0,0.0,6,-0.35,94.820945,-13.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.10,8.990012e+05,6.469797,15.847701
2019-11-30,26073.0,0.0,7,10.01,104.312522,-1.06,5.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.50,2.883067e+05,7.243518,19.164546
2019-12-31,25847.0,0.0,8,-0.87,103.405003,8.67,-0.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.58,1.050507e+05,6.654895,18.822885
2020-01-31,27076.0,0.0,9,4.75,108.316740,14.23,-1.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.55,5.153301e+04,6.314968,18.944904
2020-02-29,26619.0,0.0,10,-1.69,106.486188,2.08,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.70,2.698644e+04,5.991854,18.947907
2020-03-31,24915.0,0.0,11,-6.40,99.671072,-3.61,4.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.81,1.504458e+04,6.113191,20.275159
2020-04-30,28828.0,0.0,12,15.71,115.329397,6.47,21.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.65,1.143294e+04,7.440775,25.775599
2020-05-31,32692.0,0.0,13,13.40,130.783536,22.82,25.38,32.28,NaN,NaN,NaN,NaN,NaN,NaN,32.28,8.889620e+03,7.863094,28.350787
2020-06-30,33935.0,0.0,14,3.80,135.753310,36.20,31.28,30.44,NaN,NaN,NaN,NaN,NaN,NaN,37.30,6.630880e+03,7.535290,28.194472
2020-07-31,35579.0,0.0,15,4.84,142.323771,23.41,31.40,29.58,NaN,NaN,NaN,NaN,NaN,NaN,43.95,5.179850e+03,7.261746,28.124620
2020-08-31,35489.0,0.0,16,-0.25,141.967961,8.55,33.32,34.65,NaN,NaN,NaN,NaN,NaN,NaN,43.59,4.012850e+03,7.043937,28.175750
2020-09-30,35621.0,0.0,17,0.37,142.493243,4.96,42.96,49.75,NaN,NaN,NaN,NaN,NaN,NaN,44.12,3.213790e+03,6.829255,28.157741
2020-10-31,36565.0,0.0,18,2.65,146.269314,2.77,26.83,54.26,NaN,NaN,NaN,NaN,NaN,NaN,47.94,2.676100e+03,6.612470,28.054335
2020-11-30,37220.0,0.0,19,1.79,148.887534,4.87,13.84,42.73,NaN,NaN,NaN,NaN,NaN,NaN,50.59,2.256850e+03,6.417409,27.972838
2020-12-31,39760.0,0.0,20,6.82,159.041664,11.61,17.15,53.80,NaN,NaN,NaN,NaN,NaN,NaN,60.86,1.993660e+03,6.315258,28.242691
2021-01-31,41545.0,0.0,21,4.49,166.182635,13.61,16.76,53.42,NaN,NaN,NaN,NaN,NaN,NaN,68.08,1.757400e+03,6.159595,28.226808
2021-02-28,43421.0,0.0,22,4.52,173.694090,16.66,22.35,63.11,NaN,NaN,NaN,NaN,NaN,NaN,75.68,1.566100e+03,6.015277,28.214148
2021-03-31,42025.0,0.0,23,-3.22,168.101140,5.70,17.97,68.66,NaN,NaN,NaN,NaN,NaN,NaN,70.02,1.349330e+03,6.012974,28.837209